// Copyright (c) 2018, The TurtleCoin Developers
// Copyright (c) 2019, AlgerSoft (Kriegerrand Developers)
// Please see the included LICENSE file for more information

#pragma once

const std::string windowsAsciiArt =
"\n  \n"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxWXKKKK0ocxk;              'xx:.  .. 'xK0KKK00KKK000kc. ..,oO00x'.oxl;. ...,ox:   ...ckKKKK0000Kd.lWxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxWXKKKKd;o0x.               ..  ... .l0K00K000K00kxoll:. ..'ckK0c.c0K0ko;. ..,c;     .'o000KKK0Kk,lWxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxWXK0Kx,:OKo.             .,;'..    ,O000000Oxollc:;;;,'.  ..;oOl.;OK0000kl'. .'.      .l000000K0clNxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxWXKK0:.d00d.             :OO:.     l0K00000Oxxk00K0000Oxc. ...,,.;OK00K0o::;.    .::.  .cO00000KxoKxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxNX0Kx';k0Kx.             .cOl.    .oKKK000KKKK0Okxxxxk000x' ...  ,OK0KK0o'.''..   .dk;  .l00KK0KOokxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxWNK00l.:000k,        ...   .ld.    .oKKK0000KOo;.......,lk0x'..'. ;OK0KKK00OOOOkd;. ,ko.  .dK0K00OcdWxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxWXKK0:.lKK00l.       ..     .cc.   .lKK0kxddc'           .:dd' .. :0K0000KK00KK0K0dcdOc    c0000Kk;oxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxNK0Kk,.dKK0Kk,  .'.           '.    c000l.    '.    .;o;...ckd.  .l00K000K0xlc:cx0000O,   .d0000Kd'dxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxWNK0Ko.'kK0KK0d,.... ...             .d0Kx:,,:dk:...  ,o;,oxOK0o. .dK0000KO:.     ,lk0x.   ;OK000Kc.kxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxWXKKKo..xK0KKKK0:      ;:             .dK0000K00o.ld.    .dK0K00x';kK0KK00O:.   ..  'xd.   'k0OOKO:cXxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxWXK0KO:.:0KKKKK0Kl      .c.             ;OKKK000Kx':Ol','.:O00KKK0kk00000000c    ,l,,ox;    :xc'lkllKxxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxNKK0Kd.'xKK0K000Ko.      '.           .''o0K0K0Kkl'.lkxl;:kKKK0KKKK00KKKK0Kk;,'  ..;k0c.    .. 'c;cXxxxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxWXKKK0: :0K0KK000Kx'       .    .;'    ,kkk0K000KOo,......;d00000KKK00KKKK0Kk;cd.. .d0o.       ;o;cKxxxxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxWNK000d..dK0K0kk0K00l            .lOl.   c0KKKKKK00K0kdollodk00KK00KKKKKKKK0xc.'l;.'d0x.       :d;:0xxxxxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxWXK00O; :0K0K0xdOK0Kx,            ;O0o..',xK0KKKK00000KKKKKK000KKKKKK0000KK0kl;..';d0k,       ';,oXxxxxxxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxxxxxxxxxxxxxxWNKKK0o..dK0KKK0kOOO00k;           .lOk',kkOK0KKKK00000KK000000KKKKKKKKK00KK0000OO00K0c       .'cOWxxxxxxxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxxxxxxxxxxxxxWNK0KKx'.:O0KKKK0OOOO0K0x:.           .;..dK00KKKK0000KK00000KKKKKKKKKK0KK0K00000KKK00o.       ;OWxxxxxxxxxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxxxxxxxxxxxxxWXKK0k, ;xO0KKKOkxO0kkkOkodd,.            c0K00K00K00K0000KKKKKKK000KKOxdk0000KKK00K0o.       '0xxxxxxxxxxxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxxxxxxxxxxxxxNK0KO; 'oddxk0KOddkkdodddlldoc,..         .o000KKK0KK0K00KKKKKKK00KKKKOxxO0KKKKKKK0k:.       .dWxxxxxxxxxxxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxxxxxxxxxxxxWX00O;..:loolloxkkxxdoodxkkoodddoc,.        .;d000000KKK0KK00dccok0KKKK0O0KK0K0KK0k:.         ,Kxxxxxxxxxxxxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxxxxxxxxxxxWNK0k;.,oddollollddddddkOxlllldxxolcl:'.       .'cdx0K0000KKK0Oxoccollllllx00000Od;.           ,Kxxxxxxxxxxxxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxxxxxxxxxxxWX0x, .okOxlcllollooxxoool;.':lclllcc:;...         .,cx00KKKKK000000OkxkO0000Od:'              '0xxxxxxxxxxxxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxxxxxxxxxxxWXx, .clclccccclcc:cdxollcc;..':lc:c:;,...         .;c::cxO0K000K00K000000ko;.                 '0xxxxxxxxxxxxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxxxxxxxxxxxXx' ':c::::::::::::c:;,'';cc:. ..;::;;;;;'.         .o0xc:,:xOKKKKKK0KOxo;.  ..                lNxxxxxxxxxxxxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxxxxxxxxxxK:..,;:;,;:::::::::::;,. .'..;;'   .',,;;;;'.         .o0KOdc:::ldddolc,.    'l'               :Xxxxxxxxxxxxxxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxxxxxxxxxK; .;:::;;;;;;::::;;;,,..:kOo;..''.   ..'',,,,'.         ;kK0K0koolcclldd;    :0x'             .xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxxxxxxxWk,.:dc,;::::;,,,;::;;:,..cO0KKOo' .,'.     .''',,''.       ,kK0KKKK0000KK0ko:. c00x'            .xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxxxxxxXo..;lc'.,;colc:;::::::,. :O00KKK0k:..','.      ..'',,''.     'd0KKK000000KKKK0: :0OOk,   ..       dxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxxxxxNl..,;,...,,:llc:::;:cc:. ,kK0000KK0Ol. .,,.        ...'','.    ,dxk0KKK0KKOkOkd:..cccl:.  .'.      :Nxxxxxxxxxxxxxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxxxXx,..,,,. .,,,,;:;,,;:cc:' .o00K00K0000Oc. .'...           .....  .ckOOkOKK00OO0kl'. .,:::c,.';.      ,0xxxxxxxxxxxxxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxxxNx'..',,.  .,:;,,,,,,;;:cc:..c0K0K00K000Oxdc. .,'.              ..   :OOxdx00OOOOx;.    .;clllllc.      .dWxxxxxxxxxxxxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxxWKc. .',..   ';:;;,,'',;;:::' ,k00KK0KKK0kddddo,..,;'.           ..    :dxO0Okxk00k:..      ;loooo:.       .dNxxxxxxxxxxxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxxxWK; ..'..    .'''''',;,''';;'..dK00KK0000koolclxxc...;;..         .,'  .l000000000Kkoxkoc;;' .:cccc'          lNxxxxxxxxxxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxxWNO:..'..     ......'.',''..... :00000KK0Oxolc''cox0x;..';,..         ,;.,k000K000KKKK0000KK0O: .;;;;.          .cKWxxxxxxxxxxxxxxxxxxxxxxx  \n"
"xxxxxxxxW0c...'.      ................. .x00KKKK0koool,.,lldO0ko:...',.         ,ldOKKK0KK000KK0K0KKK0Kd..,;;'    .        cNxxxxxxxxxxxxxxxxxxxxxxx  \n"
"xxxxxxxNx' ..        ...''............  :0K0KK00xolll;..:cclxkxkOx:....'.       .lO00K00KK00K00KKKKK00Kd. ';'.  .';,,'     :Xxxxxxxxxxxxxxxxxxxxxxxx  \n"
"xxxxxWKl. .     ',  .............',,'. .oKK00K0kllll:..:lc::ldxkOOdoo,. ...      'dO0K0000KK0KK00000000l..''.   .,::;.    .kWxxxxxxxxxxxxxxxxxxxxxxx  \n"
"xxxxNk;.     .ckKc ...........'''.''.. ,kKKK00Oolllc. .::::::dkxddooxoc,.         ;dO0KKKKKKOxk000000Kk'  . .;;. .,,.    .dWxxxxxxxxxxxxxxxxxxxxxxxx  \n"
"xxxxk.     .oKWWk. .''''''''''''''''...lOOxdooollll, .,::::::lxxollllcllc;'.      .:oxO0O0KKOc:k0KK000c.  .:c:,. .,,.    .xWxxxxxxxxxxxxxxxxxxxxxxxx  \n"
"xxx0,     ;0WxWK; .','''''''''';oooocoxdkxclxxlcccc,. .:::::::lxkxddkkkxxxxdo;.    ,oodxdk000Ol,:x000Ol.'ckOdl;.  ..   .. ;Xxxxxxxxxxxxxxxxxxxxxxxxx  \n"
"8 8888     ,88' 8 888888888o.    8 8888 8 8888888888       ,o888888o.    8 8888888888   8 888888888o.   8 888888888o.            .8.          b.             8 8 888888888o.  \n"
"8 8888    ,88'  8 8888    `88.   8 8888 8 8888            8888     `88.  8 8888         8 8888    `88.  8 8888    `88.          .888.         888o.          8 8 8888    `^888.  \n"
"8 8888   ,88'   8 8888     `88   8 8888 8 8888         ,8 8888       `8. 8 8888         8 8888     `88  8 8888     `88         :88888.        Y88888o.       8 8 8888        `88.  \n"
"8 8888  ,88'    8 8888     ,88   8 8888 8 8888         88 8888           8 8888         8 8888     ,88  8 8888     ,88        . `88888.       .`Y888888o.    8 8 8888         `88  \n"
"8 8888 ,88'     8 8888.   ,88'   8 8888 8 888888888888 88 8888           8 888888888888 8 8888.   ,88'  8 8888.   ,88'       .8. `88888.      8o. `Y888888o. 8 8 8888          88  \n"
"8 8888 88'      8 888888888P'    8 8888 8 8888         88 8888           8 8888         8 888888888P'   8 888888888P'       .8`8. `88888.     8`Y8o. `Y88888o8 8 8888          88  \n"
"8 888888<       8 8888`8b        8 8888 8 8888         88 8888   8888888 8 8888         8 8888`8b       8 8888`8b          .8' `8. `88888.    8   `Y8o. `Y8888 8 8888         ,88  \n"
"8 8888 `Y8.     8 8888 `8b.      8 8888 8 8888         `8 8888       .8' 8 8888         8 8888 `8b.     8 8888 `8b.       .8'   `8. `88888.   8      `Y8o. `Y8 8 8888        ,88'  \n"
"8 8888   `Y8.   8 8888   `8b.    8 8888 8 8888            8888     ,88'  8 8888         8 8888   `8b.   8 8888   `8b.    .888888888. `88888.  8         `Y8o.` 8 8888    ,o88P'  \n"
"8 8888     `Y8. 8 8888     `88.  8 8888 8 888888888888     `8888888P'    8 888888888888 8 8888     `88. 8 8888     `88. .8'       `8. `88888. 8            `Yo 8 888888888P'  \n"
"49 6E  4D 65 6D 6F 72 79  4F 66  50 69 67 6C 65 79  49 49		WE DONT ASK WHAT YOULL USE IT FOR		ALGERSOFT.ORG KRIEGERRAND.COM                      \n"
"\n					\n";

const std::string nonWindowsAsciiArt = 
"\n				\n"                                                                                                                      
"                                                                            ............                                       \n"
"  .                                                                   ..'',,;;;;;;;;;;;,,'...                                  \n"
" .okc.                                                              .',,,,,,,,,,,,,,,,..',;;,'.                                \n"
" .xNXOl.                                                          .,;,,:odddddddddddc,....',;;;,.                              \n"
" .kXXXX0l.                                                      .';;,:okNNNNNNNNNNNNKxo:....',;;;,.                            \n"
" .kNXXXXX0l.                                                  ..,;;,;kXxccckXNNKdcclONXd,,'...',;;,,.                          \n"
"  cKXXXXXXX0l.                                               .;;;;,,xN0;   lXNNO'  .oNNXo,;,'...',;;;,.                        \n"
"   cKXXXXXXXXOl.                                             .;;;;,,oKXxcclkXNNKdcclONN0l,;;;,'...',,;.                        \n"
"    lKXXXXXXXXXOc.                                           .;;;;;,,o0KKNX00KXKO0XNKOOl,,;;;;;,'...,;'.                       \n"
"    .lKXXXXXXXXXXOc.                                        .';;;;;;,;:;lOx;,d0l':k0l,;;;;;;;;;;;,,,,;,;'                      \n"
"     .cOXXXXXXXXXXKx:.                             ...     .,,;;;;;;;;;,,:;,,;:;,,;:;,;;;;;;;;;;;;;;;;,;'                      \n"
"       .cOXXXXXXXXK0Ox:.                         .,;;;'.   .;,,,,;,,,,,;;;;,,;;;,;;;;,,;,,;,,;;;;;;;;;;;,.                     \n"
"         .cOXXXXXXK0OOOx:,''''.                 .;;;;;;;,. .;cllllllllllllllllc:lllllllllllllc;,;;;;'.'...                     \n"
"           .lOXXXXK0OOOOOOOkOk:                .,;;;;;;::;',lkOOOkxxxkOOOOOOOOkookOOOOkxxxxkOko:,;;,... .........              \n"
"             .lOXXK0Okkxddddl'                 .,;;;;;;;;;;;oOOOOd:::;cxOOOOOOOkdodxxc,,,,,lkOkl;;:cc;'':oddddddc'.            \n"
"               .lO0Okxddooddo'                 .,;;;;;;;;;,;oOOOOOOOOd;,ckOOOOOOOkl::;;:::::lxOdldkkOxcldc:ldddc:o:            \n"
"                 :ddddoddxxxdo:.               .,;;;;;;;;;;:dOOOOOxlcoko;:xOOOOOOo;;::;::::;:oOOOOOOOklod:.'oxdold:            \n"
"                ;oooooddxxxxxxxx:              .,;;;;;;;;;;oOOOOOOo'.;xOkkOOOOOOOkxdc:;;:;;;cdOOOOOOOxlodl:lxxxxxd,            \n"
"               .ldoodkxxxxdxxxxxo.              ..........'lOOOOOOxlldkOOOOOOOOkOOOOxdddodoclxOOOOOOOd:odddl:;;:oxl'           \n"
"               .ldoodxxddxxxxxxdoc,.                       ;Okdc,,,,;,,,,,,,,,,,,,,,,,,,,,,'.',,;cllc:coddd;    ..'.           \n"
"               .:ooodxxxxxxxxdoollol;.                     .;,'. ,oooddoodooodoodo,...:ddo;;;...'''',ldddddol,                 \n"
"                 'coddxxxxxdooloooolol;.                     ..,;dNWWWWWWWWWWWWWWKololOWNd;cc;:oxxxxxdddddddddc.               \n"
"                  .,ldddddoolllloolllool:.                   .'lxdk0K00KK00K00KK0O0XNKO0O::xkxxxxxxxxddddddddddoc:::::cl;.     \n"
"                    .',,;:clllllllllolllll:'                 .,lkddxkxxkkxxkxxkkxxkxxkxxo,ckd:cxxxxxxdddddddddxxxxxxxooxo.     \n"
"                         ,::clllllllloolllol:'.              ..;c:::::::c::c::::c:::c::c;.:do'.okxxxxdddddddddxxxxxxx;.od.     \n"
"                          .;:cccllollollllololc,.                                         .....'codxxdddddddddo;''...  ..      \n"
"                           ..;cccloooollllllollllc::cc:::c:'......                          .''.,cccoddddddddc.                \n"
"                             .';:ccclollllloolllllllllllllc::cooc'..                      ..;ll:,,;:ccccllc;'.                 \n"
"                               .,,,;cllloolllollllloollcc::::loolll;.....            .....:llllol:';;''',;'                    \n"
"                                   .;:ccllllolllllllllc::::::loollllllol,............'cllllllllloo;;c'.'','                    \n"
"                                    ..,;;;cllllllcc::::::::::loolooldO00Okkkkkkkkkxlccllllloollloo;,,';:'..,,.                 \n"
"                                         .,:cccc:::::::::::::loolloldOKKKKKK0KKKKK0dlollllolllccllllcllllcllol;.               \n"
"                                           .................'coolloldOKKKKK0kOKKKK0dlollllllolc::clolllllollllll:.             \n"
"                                                            .coolloldOKKKKKK00KKKK0dlollllllllc::::cllllloollllllc,.        \n"
"                      '##:::'##:'########::'####:'########::'######:::'########:'########::'########:::::'###::::'##::: ##:'########::  \n"
"                       ##::'##:: ##.... ##:. ##:: ##.....::'##... ##:: ##.....:: ##.... ##: ##.... ##:::'## ##::: ###:: ##: ##.... ##:  \n"
"                       ##:'##::: ##:::: ##:: ##:: ##::::::: ##:::..::: ##::::::: ##:::: ##: ##:::: ##::'##:. ##:: ####: ##: ##:::: ##:  \n"
"                       #####:::: ########::: ##:: ######::: ##::'####: ######::: ########:: ########::'##:::. ##: ## ## ##: ##:::: ##:  \n"
"                       ##. ##::: ##.. ##:::: ##:: ##...:::: ##::: ##:: ##...:::: ##.. ##::: ##.. ##::: #########: ##. ####: ##:::: ##:  \n"
"                       ##:. ##:: ##::. ##::: ##:: ##::::::: ##::: ##:: ##::::::: ##::. ##:: ##::. ##:: ##.... ##: ##:. ###: ##:::: ##:  \n"
"                       ##::. ##: ##:::. ##:'####: ########:. ######::: ########: ##:::. ##: ##:::. ##: ##:::: ##: ##::. ##: ########::  \n"
"                      ..::::..::..:::::..::....::........:::......::::........::..:::::..::..:::::..::..:::::..::..::::..::........:::  \n"
"                                                                      .dXXXd,,,,,..                   'dkxxxxxxxxxxxxd'        \n"
"                                                                      .dXXXd,''''.                    .oxxxxxxxxxxxxxd,        \n"
"                                                            ..........'o000OOOkkkl...................  ;xxxo;;dxxxxxxx,        \n"
"                                                           .:lllllllllllooooooooollllllllllll:;;;;;;.   ';'. 'oxxxxdxx,        \n"
"                                                           .collllllllllllollooolllolllllllllc::::::'       .lxxxxdxd:.        \n"
"                                                           .collollolllllllcccclllloolooloolllc:::;:,       .;loooo:.          \n"
"                                                           .colllllolllc:c:;,'';lllllloolollllc:::;:,           ..             \n"
"                                                           .colllllllll:::,.  .;lllllllllllllc;::::;'                          \n"
"                                                           .;lolllllllc::;.   .:lllllllllllllc:::::,.                          \n"
"                                                             .';cllllc:::'     .,:cccccccccccc:::::,.                          \n"
"                                                               .;looolc:;.      ,lclcccccccccc:::::,                           \n"
"                                                                 .,cl:'.        'cccccccccccccc::;,.                           \n"
"                                                                  .:l'          .:llllllllllllll,.                             \n"
"                                                                  .:o'           .,lxxxxolllllll'                              \n"
"                                                                  .:o'            .cxkkkdllolol;.                              \n"
"                                                                  .:l'           .:lodddolloloc.                               \n"
"                                                                  .:l'         .:llllooollloloc.                               \n"
"                                                                   ;l.        .clcllllllllllcl:.                               \n"
"                                                                    .          ................                                \n"
"                              ______     __         ______     ______     ______     ______     ______     ______   ______          \n"                                                                                                                                                                      
"                             |\  __ \   |\ \       |   ___\   |\  ___\   |\  == \   |\  ___\   |\  __ \   |\  ___\ |\__  _\ .ORG         \n"                                                                                                                                                                   
"                             \ \  __ \  \ \ \____  \ \ \__ \  \ \  __\   \ \  __<   \ \___  \  \ \ \|\ \  \ \  __\ \|_|\ \|                   \n"                                                                                                                                                              
"                              \ \_\ \_\  \ \_____\  \ \_____\  \ \_____\  \ \_\ \_\  \|\_____\  \ \_____\  \ \_\      \ \_\                        \n"                                                                                                                                                        
"                               \|_|\|_|   \|_____|   \|_____|   \|_____|   \|_| |_|   \|_____|   \|_____|   \|_|       \|_|     \n"
"															WE DONT ASK WHAT YOULL USE IT FOR  \n"
"\n				\n";
/* Windows has some characters it won't display in a terminal. If your ascii
   art works fine on Windows and Linux terminals, just replace 'asciiArt' with
   the art itself, and remove these two #ifdefs and above ascii arts */
#ifdef _WIN32
const std::string asciiArt = windowsAsciiArt;
#else
const std::string asciiArt = nonWindowsAsciiArt;
#endif